#!/bin/bash
#
# Rolf Niepraschk <Rolf.Niepraschk@gmx.de>, 2018-12-18
#
# Creates openSUSE src and bin rpm files for "couch-js" as a replacement for 
# "libmozjs" (spidermonkey)

# sudo zypper in mozilla-nspr-devel autoconf213

curl -sL https://github.com/apache/couchdb-pkg/archive/master.tar.gz | tar xz
cp couchdb-pkg-master/js/src/js185-?.?.?.tar.gz  \
   couchdb-pkg-master/js/rpm/SOURCES/* ~/rpmbuild/SOURCES/

rpmbuild -ba couchdb-pkg-master/js/rpm/SPECS/js.spec

rm -rf couchdb-pkg-master

exit


